export default {
  //左边相关mutation
  SET_PATIENT_INFO: 'set_patient_info',
  SET_STATE_PROP: 'set_state_prop',
  SET_RECORD_PROP: 'set_record_prop',

  //中间相关mutation
  ADD_NEW_RECIPT: 'ADD_NEW_RECIPT',//新增处方
  CHANGE_CURR_TAB: 'CHANGE_CURR_TAB',//切换处方
  CANCEL_RECIPE: 'CANCEL_RECIPE',//删除处方
  ADD_NEW_MEDICINE: 'ADD_NEW_MEDICINE',//新增药品
  MODIFY_MEDICINE: 'MODIFY_MEDICINE',//修改药品
  CANCEL_MEDICINE: 'CANCEL_MEDICINE',//删除药品
  MODIFY_RECIPE: 'MODIFY_RECIPE',//修改处方金额
  MODIFY_RECIPE_DETAIL: 'MODIFY_RECIPE_DETAIL',//修改处方附加等
  CLEAN_RECIPE: 'CLEAN_RECIPE',
  SELECT_FJB_RECIPE: 'SELECT_FJB_RECIPE',
  SET_ORDER_SEQNO: 'SET_ORDER_SEQNO',
  CHANGE_PRINT_PRE: 'change_print_pre',//'CHANGE_PRINT_PRE'
  INIT_RECIPE: 'INIT_RECIPE',
  INIT_RECODE: 'INIT_RECODE',
  SAVE_DRAFT_DATA: 'SAVE_DRAFT_DATA',
  SET_RECIPE_HELP: 'SET_RECIPE_HELP',
  SET_FJ_LIST: 'SET_FJ_LIST',
  SET_CLOUD_SHOP: 'SET_CLOUD_SHOP'


  //右边相关mutation

}
